## Copyright (C) 2011 Richard Mortier <rmm@cs.nott.ac.uk>
##
## This program is free software: you can redistribute it and/or
## modify it under the terms of the GNU Affero General Public License
## as published by the Free Software Foundation, either version 3 of
## the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public
## License along with this program.  If not, see
## <http://www.gnu.org/licenses/>.

application: homework-notify
version: 2
runtime: python27
threadsafe: false
api_version: 1

builtins:
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /notify/2/?
  script: notify.urls.application
  secure: always

- url: /notify/2/.*
  script: notify.urls.application
  secure: always

- url: /.*
  script: notfound.application
  secure: always
